[2015-04-22 05:59:59 +0000] [31634] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f15e900a2a8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f15e9081f50>
  pre_fork: <function pre_fork at 0x7f15e900a140>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: True
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f15e9081de8>
  pre_exec: <function pre_exec at 0x7f15e900a848>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f15e900a410>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f15e900aed8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f15e900a9b0>
  post_request: <function post_request at 0x7f15e900aaa0>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f15e900a578>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f15e900ac08>
  chdir: /home/ubuntu/pointlist
  paste: None
  default_proc_name: pointlist.wsgi:application
  errorlog: /home/ubuntu/pointlist/gunicorn.log
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f15e9081c80>
  worker_abort: <function worker_abort at 0x7f15e900a6e0>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f15e900ad70>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2015-04-22 05:59:59 +0000] [31634] [INFO] Starting gunicorn 19.3.0
[2015-04-22 05:59:59 +0000] [31634] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 05:59:59 +0000] [31634] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:00 +0000] [31634] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:00 +0000] [31634] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:01 +0000] [31634] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:01 +0000] [31634] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:02 +0000] [31634] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:02 +0000] [31634] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:03 +0000] [31634] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:03 +0000] [31634] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:04 +0000] [31634] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2015-04-22 06:00:40 +0000] [31641] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7fa9c264a2a8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7fa9c26c1f50>
  pre_fork: <function pre_fork at 0x7fa9c264a140>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: True
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7fa9c26c1de8>
  pre_exec: <function pre_exec at 0x7fa9c264a848>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7fa9c264a410>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7fa9c264aed8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7fa9c264a9b0>
  post_request: <function post_request at 0x7fa9c264aaa0>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7fa9c264a578>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7fa9c264ac08>
  chdir: /home/ubuntu/pointlist
  paste: None
  default_proc_name: pointlist.wsgi:application
  errorlog: /home/ubuntu/pointlist/gunicorn.log
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7fa9c26c1c80>
  worker_abort: <function worker_abort at 0x7fa9c264a6e0>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7fa9c264ad70>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2015-04-22 06:00:40 +0000] [31641] [INFO] Starting gunicorn 19.3.0
[2015-04-22 06:00:40 +0000] [31641] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:40 +0000] [31641] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:41 +0000] [31641] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:41 +0000] [31641] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:42 +0000] [31641] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:42 +0000] [31641] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:43 +0000] [31641] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:43 +0000] [31641] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:44 +0000] [31641] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:00:44 +0000] [31641] [ERROR] Retrying in 1 second.
[2015-04-22 06:00:45 +0000] [31641] [ERROR] Can't connect to ('127.0.0.1', 8000)
./start_gunicorn.sh: line 16: exec: gunicorn: not found
./start_gunicorn.sh: line 17: exec: gunicorn: not found
[2015-04-22 06:03:26 +0000] [31749] [DEBUG] Current configuration:
  proxy_protocol: False
  worker_connections: 1000
  statsd_host: None
  max_requests_jitter: 0
  post_fork: <function post_fork at 0x7f25f48e92a8>
  pythonpath: None
  enable_stdio_inheritance: False
  worker_class: sync
  ssl_version: 3
  suppress_ragged_eofs: True
  syslog: False
  syslog_facility: user
  when_ready: <function when_ready at 0x7f25f4960f50>
  pre_fork: <function pre_fork at 0x7f25f48e9140>
  cert_reqs: 0
  preload_app: False
  keepalive: 2
  accesslog: None
  group: 1000
  graceful_timeout: 30
  do_handshake_on_connect: False
  spew: False
  workers: 3
  proc_name: None
  sendfile: True
  pidfile: None
  umask: 0
  on_reload: <function on_reload at 0x7f25f4960de8>
  pre_exec: <function pre_exec at 0x7f25f48e9848>
  worker_tmp_dir: None
  post_worker_init: <function post_worker_init at 0x7f25f48e9410>
  limit_request_fields: 100
  on_exit: <function on_exit at 0x7f25f48e9ed8>
  config: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  proxy_allow_ips: ['127.0.0.1']
  pre_request: <function pre_request at 0x7f25f48e99b0>
  post_request: <function post_request at 0x7f25f48e9aa0>
  user: 1000
  forwarded_allow_ips: ['127.0.0.1']
  worker_int: <function worker_int at 0x7f25f48e9578>
  threads: 1
  max_requests: 0
  limit_request_line: 4094
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  certfile: None
  worker_exit: <function worker_exit at 0x7f25f48e9c08>
  chdir: /home/ubuntu/pointlist
  paste: None
  default_proc_name: pointlist.wsgi:application
  errorlog: /home/ubuntu/pointlist/gunicorn.log
  loglevel: debug
  logconfig: None
  syslog_addr: udp://localhost:514
  syslog_prefix: None
  daemon: False
  ciphers: TLSv1
  on_starting: <function on_starting at 0x7f25f4960c80>
  worker_abort: <function worker_abort at 0x7f25f48e96e0>
  bind: ['127.0.0.1:8000']
  raw_env: []
  reload: False
  check_config: False
  limit_request_field_size: 8190
  nworkers_changed: <function nworkers_changed at 0x7f25f48e9d70>
  timeout: 30
  ca_certs: None
  django_settings: None
  tmp_upload_dir: None
  keyfile: None
  backlog: 2048
  logger_class: gunicorn.glogging.Logger
  statsd_prefix: 
[2015-04-22 06:03:26 +0000] [31749] [INFO] Starting gunicorn 19.3.0
[2015-04-22 06:03:26 +0000] [31749] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:03:26 +0000] [31749] [ERROR] Retrying in 1 second.
[2015-04-22 06:03:27 +0000] [31749] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:03:27 +0000] [31749] [ERROR] Retrying in 1 second.
[2015-04-22 06:03:28 +0000] [31749] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:03:28 +0000] [31749] [ERROR] Retrying in 1 second.
[2015-04-22 06:03:29 +0000] [31749] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:03:29 +0000] [31749] [ERROR] Retrying in 1 second.
[2015-04-22 06:03:30 +0000] [31749] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2015-04-22 06:03:30 +0000] [31749] [ERROR] Retrying in 1 second.
[2015-04-22 06:03:31 +0000] [31749] [ERROR] Can't connect to ('127.0.0.1', 8000)
